name: "Release Changes"
description: "GitHub Actions for checking changes between releases"
branding:
  icon: "tag"
  color: "orange"
inputs:
  sha:
    description: "The commit SHA that triggered the workflow run"
    required: false
    default: ${{ github.sha }}
  ref_name:
    description: "The branch or tag name that triggered the workflow run"
    required: false
    default: ${{ github.ref_name }}
outputs:
  changes:
    description: "Indicates if there are changes from the latest release"
    value: ${{ steps.run.outputs.changes }}
  latest:
    description: "The lastest release on the workflow branch"
    value: ${{ steps.run.outputs.latest }}
runs:
  using: "composite"
  steps:
    - id: run
      run: $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.sha }} ${{ inputs.ref_name }}
      shell: bash
