name: Release Changes Action
description: |
  Detects changes between releases by looking at new commits from the last tag on a given branch. This
  can be helpful for skipping upload of nightly builds etc.
branding:
  icon: wind
  color: orange
author: Jeppe Frandsen
inputs:
  sha:
    description: "The commit SHA that triggered the workflow run"
    required: false
    default: ${{ github.sha }}
  ref_name:
    description: "The branch or tag name that triggered the workflow run"
    required: false
    default: ${{ github.ref_name }}
outputs:
  changes:
    description: "Indicates if there are changes from the last release"
    value: ${{ steps.run.outputs.changes }}
runs:
  using: 'composite'
  steps:
    - id: run
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.sha }} ${{ inputs.ref_name }}
      shell: bash
